FROM pytorch/pytorch:latest

RUN apt-get update && \
    apt-get install nginx -y && \
    pip install supervisor

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN mkdir /app
WORKDIR /app

RUN mkdir /prom
ENV PROMETHEUS_MULTIPROC_DIR=/prom

COPY supervisord.conf /etc/supervisord.conf
COPY configuration.nginx /etc/configuration.nginx
COPY server.py gunicorn.py gpt2.py train_gpt2.py fineweb.py hellaswag.py gunicorn.py /app/

ENTRYPOINT ["supervisord", "-c", "/etc/supervisord.conf"]