FROM pytorch/pytorch:latest

RUN apt-get update && \
    apt-get install -y nginx curl && \
    pip install supervisor && \
    curl -sSL https://install.python-poetry.org | python3 -

ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app
COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root

RUN mkdir -p /app /prom /etc/grafana /etc/prometheus
ENV PROMETHEUS_MULTIPROC_DIR=/prom

COPY supervisord.conf /etc/supervisord.conf
COPY configuration.nginx /etc/nginx/conf.d/default.conf
COPY server.py gunicorn.py gpt2.py train_gpt2.py fineweb.py hellaswag.py /app/
COPY grafana /etc/grafana
COPY prom/prometheus.yml /etc/prometheus/prometheus.yml

RUN poetry shell

ENTRYPOINT ["supervisord", "-c", "/etc/supervisord.conf"]
